import { DM_Sans } from "next/font/google";
import "./globals.css";

const inter = DM_Sans({ subsets: ["latin"] });
import Navbar from "./navbar";
export const metadata = {
  title: "Fasha Fadillah Portfolio's",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-4 md:px-8 xl:px-0`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
